### ISSUE TITLE
Plugin ZendDeveloperToolsTime have no alias

### ISSUE THREAD

**Issue by malinink** [zendframework/ZendDeveloperTools#221]
There is plugin call [here](https://github.com/doctrine/DoctrineORMModule/blob/master/view/zend-developer-tools/toolbar/doctrine-orm-queries.phtml#L8).
With SM3 that call rises exception ```A plugin by the name "zendDeveloperToolsTime" was not found in the plugin manager```

There is two ways to fix problem - add alias, modify a call. I think that alias is better solution. I'll add PR.

**Comment by bitwombat** [comment]
Good catch @malinink !  You just saved me, many thanks.

In my case, I think doctrine2 is calling it with the lowercase 'z'.

`vendor/doctrine/doctrine-orm-module/view/zend-developer-tools/toolbar/doctrine-orm-queries.phtml
8:            <?php echo $this->zendDeveloperToolsTime($collector->getQueryTime()); ?>
`

Shouldn't that be where the fix is, rather than an alias in zend-developer-tools/src/Module.php?

**Comment by MatthiasKuehneEllerhold** [comment]
There is a PR for Doctrine 2 here: https://github.com/doctrine/DoctrineORMModule/pull/496

**Comment by malinink** [comment]
Fixed in Doctrine
