### ISSUE TITLE
An exception was raised while creating "ZendDeveloperTools\DbCollector"; no instance returned

### ISSUE THREAD

**Issue by ghost** [zendframework/ZendDeveloperTools#54]
DB collector doesn't work with default options. I have set to ['collectors]['db'] => 'ZendDeveloperTools\Collector\DbCollector'

But eg. for time collector it doesn't matter if I use ZendDeveloperTools\TimeCollector or ZendDeveloperTools\Collector\TimeCollector

I don't know what is wrong.

**Comment by Mairu** [comment]
This happens when Zend\ServiceManager\Di\DiAbstractServiceFactory (with RuntimeDefinition) is configured as abstract factory within the service manager and the di is not configured to instantiate Zend\Db\Adapter\Adapter.

I worked around it by writing a blacklist abstract factory proxy for the DiAbstractServiceFactory so i can set classes that cannot be created.
